# Generated by Django 3.2.5 on 2022-04-05 14:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=32)),
                ('col', models.CharField(max_length=32)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('label_sv', models.CharField(blank=True, max_length=255, null=True)),
                ('ftab', models.CharField(blank=True, max_length=32, null=True)),
                ('fcol', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('hidden', models.PositiveIntegerField()),
                ('readonly', models.PositiveIntegerField()),
                ('searchable', models.PositiveIntegerField()),
                ('help', models.CharField(max_length=256)),
                ('help_sv', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'col_labels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.CharField(blank=True, max_length=128, null=True)),
                ('bildfil', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(blank=True, max_length=175, null=True)),
            ],
            options={
                'db_table': 'motive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objektid', models.CharField(blank=True, max_length=128, null=True, verbose_name='Objekt ID')),
                ('museum', models.CharField(blank=True, max_length=128, null=True, verbose_name='Museum')),
                ('inventarienummer', models.CharField(blank=True, max_length=128, null=True, verbose_name='Inventarienummer')),
                ('undernummer', models.CharField(blank=True, max_length=128, null=True, verbose_name='Undernummer')),
                ('invnr', models.CharField(blank=True, max_length=128, null=True, verbose_name='Inventarienummer')),
                ('landskap', models.CharField(blank=True, max_length=128, null=True, verbose_name='Landskap')),
                ('ort', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ort')),
                ('sakord', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sakord')),
                ('typ', models.CharField(blank=True, max_length=128, null=True, verbose_name='Typ')),
                ('undertyp', models.CharField(blank=True, max_length=128, null=True, verbose_name='Undertyp')),
                ('cdh_category', models.CharField(max_length=16, verbose_name='CDH-Kategori')),
                ('objekt', models.CharField(blank=True, max_length=128, null=True, verbose_name='Objekt')),
                ('namntyp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Namntyp')),
                ('upphovsman', models.CharField(blank=True, max_length=128, null=True, verbose_name='Upphovsperson')),
                ('tid', models.CharField(blank=True, max_length=128, null=True, verbose_name='Tid')),
                ('lk_tid', models.CharField(blank=True, max_length=128, null=True, verbose_name='Tid (lk)')),
                ('dat_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tidigaste datum')),
                ('dat_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Senaste datum')),
                ('hojd', models.CharField(blank=True, max_length=128, null=True, verbose_name='Höjd')),
                ('bredd', models.CharField(blank=True, max_length=128, null=True, verbose_name='Bredd')),
                ('material', models.CharField(blank=True, max_length=128, null=True, verbose_name='Material')),
                ('delar', models.CharField(blank=True, max_length=128, null=True, verbose_name='Delar')),
                ('urtappning', models.CharField(blank=True, max_length=128, null=True, verbose_name='Urtappning')),
                ('inskrift', models.CharField(blank=True, max_length=256, null=True, verbose_name='Inskrift')),
                ('kondition', models.CharField(blank=True, max_length=512, null=True, verbose_name='Kondition')),
                ('farg', models.CharField(blank=True, max_length=256, null=True, verbose_name='Färg')),
                ('ovrigt', models.TextField(blank=True, null=True, verbose_name='Övrigt')),
                ('sokord', models.CharField(blank=True, max_length=512, null=True, verbose_name='Sökord')),
                ('motiv', models.TextField(blank=True, null=True, verbose_name='Motiv')),
                ('litteratur', models.TextField(blank=True, null=True, verbose_name='Litteratur')),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='Status')),
                ('titel', models.CharField(blank=True, max_length=128, null=True, verbose_name='Titel')),
            ],
            options={
                'db_table': 'object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('variants', models.CharField(blank=True, max_length=256, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('diocese', models.CharField(blank=True, max_length=255, null=True)),
                ('diocese_med', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('notbefore', models.CharField(blank=True, max_length=16, null=True)),
                ('notafter', models.CharField(blank=True, max_length=16, null=True)),
                ('note_year', models.CharField(blank=True, max_length=128, null=True)),
                ('snid_4', models.PositiveIntegerField(blank=True, null=True)),
                ('wikidata', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'parishes',
                'db_table': 'parish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.PositiveIntegerField()),
                ('certainty_type', models.CharField(max_length=9)),
                ('certainty', models.CharField(max_length=9)),
                ('date_bebr', models.CharField(max_length=64)),
                ('notbefore', models.CharField(max_length=32)),
                ('notafter', models.CharField(max_length=32)),
                ('type_indication', models.CharField(max_length=8)),
                ('note_year', models.CharField(max_length=128)),
                ('wikidata', models.CharField(blank=True, max_length=64, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('municipality', models.CharField(blank=True, max_length=256, null=True)),
                ('county', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exclude', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
    ]
